font-size: 13px
max-width: 500px

button-color: inherit  # matches text color
theme: light           # light, dark,  custom

# To set custom colors for footnote uncomment and change the values below:
#background: '#fff' # footnote popover background
#text: '#444'       # popover text color
