theme: light           # light or dark

# To override footnote theme colors uncomment and change the values below:
#background: '#fff' # footnote popover background
#text: '#444'       # popover text color

button-color: inherit  # matches text color

font-size: 13px
max-width: 500px
