style: light

light:
  background: '#fff' # footnote popover background
  text: '#444'       # popover text color
  button: inherit    # matches text color

dark:
  background: '#444' # footnote popover background
  text: '#ccc'       # popover text color
  button: inherit    # matches text color
